### ISSUE TITLE
Spring Boot 3.1.0-M1 shows up with wrong status

### ISSUE THREAD

**Issue by martinlippert** [spring-io/projects-api#12]
The milestone build Spring Boot 3.1.0-M1 shows up with a status `GENERAL_AVAILABILITY`. I think it should be `PRERELEASE` instead.

https://api.spring.io/projects/spring-boot/releases/3.1.0-M1

**Comment by mbhave** [comment]
@martinlippert This should be fixed now https://api.spring.io/projects/spring-boot/releases/3.1.0-M2.

**Comment by martinlippert** [comment]
Awesome, many many thanks for the update and the fix! Much appreciated!!!
