### ISSUE TITLE
API project generation resource for projects with null support policy from Contentful throws 500

### ISSUE THREAD

**Issue by mbhave** [spring-io/projects-api#18]
https://api.spring.io/projects/spring-pulsar/generations -> 500

cc @odrotbohm

**Comment by odrotbohm** [comment]
Are you sure it's that? Spring Modulith doesn't define any support ranges either but [returns a 200](https://api.spring.io/projects/spring-modulith/generations) with an "empty" response.

**Comment by mbhave** [comment]
It's that in combination with the support policy defined. Spring Pulsar has `UPSTREAM` and Spring Modulith has `SPRING_BOOT`. That makes pulsar return `null` when contentful is queried for the support policy but modulith returns an empty list. 

I need to check what the implementation of `UPSTREAM` and `SPRING_BOOT` is with @dvitrac but for this issue we need to fix the 500 if contentful returns `null`.

**Comment by anthonydahanne** [comment]
hello 👋 
Just to say we are impacted by this issue over at Paketo Buildpacks
https://github.com/paketo-buildpacks/spring-boot/actions/runs/6844922071/job/18627189425#step:4:7

Thanks and good luck 🤞
