### ISSUE TITLE
Imprecision of in release status documentation

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/projects-api#6]
The release status contains a value `GENERALLY_AVAILABLE` to indicate a publicly available release. However, we've been incentivized not use the term for projects in incubation status. Does it make sense to introduce a new status to indicate that difference? As a short-term measure, we could also simply update the documentation for that particular status to indicate that projects are only fully supported if they're in the `ACTIVE` state.

**Comment by mbhave** [comment]
Closing this as we can make a UI change to show Incubating project.
